### ISSUE TITLE
httpBasicAuthString

### ISSUE THREAD

**Issue by Yoruba** [avid-technology/ctms-examples-node#3]
Is the code in this repository still up to date for MediaCentral 2020.9?
If yes for authorization a httpBasicAuthString string is needed.
What contains this string?
client_id:client_secret

What is the client_id and client_secret or where can I get it?

This doesn't work for me

```javascript
var authorizationDefaultToken = 'Basic ' +  Buffer.from('username:password').toString('base64');
```

``` javascript
{
      error: 'invalid_client',
      error_description: 'Unknown client or client authentication failed.'
}
```

Thanks

**Comment by tilmans** [comment]
Hi, the basicauth is used to identify your client, not the user. You have to register your client id with by Avid for the system to accept your calls. Check other client's calls, for example Cloud UX, to CTMS.

Search here for "client_id": http://developer.avid.com/upstream/platformAuthorization/documentation-public/md/authentication.html

**Comment by Yoruba** [comment]
Thanks tilmans, for your help.

Does all apps to be register at Avid? 
The application which I have to build is not embedded in the Cloud UX GUI.
It's just a service which call the API without user interaction.

**Comment by tilmans** [comment]
I'm not sure what the official policy is, it's best to contact Avid developer support.
